## Application Storage Basics
たとえば、データベースをホストするために、OpenShift のポッドが信頼できるストレージを必要とする場合、ポッドに **永続** ボリュームを提供する必要があります。 このタイプのストレージはコンテナーよりも長く存続します。つまり、ポッドが終了しても存続します。 通常、外部ストレージ システムから取得されます。

[Warning]
====
これらの演習を行うには、アプリケーション管理の基本演習で取り上げたアプリケーションをすでにデプロイしている必要があります。 続行する前に、これらの演習を今すぐ行う必要があります。
====

`mapit` アプリケーションは現在、永続ストレージを利用していません。 Pod が死ぬと、コンテナ内のすべてのコンテンツも死にます。

この概念については、後で詳しく説明します。 しかし、しばらく想像してみましょう。`mapit` アプリケーションは、コンテナ内の `/app-storage` ディレクトリの下で利用可能な永続的なストレージを必要とします。

[Note]
====
コンテナーの内部ファイルシステムを構成するディレクトリは、コンテナー イメージの読み取り専用レイヤーと、コンテナー インスタンスがイメージから開始されるとすぐに追加される書き込み可能な最上位レイヤーのブレンドです。 動的なコンテナー オーケストレーション環境では、コンテナーが削除されると、書き込み可能なレイヤーは破棄されます。
====

前のラボの「app-management」プロジェクトにいる必要があります。 確認するには、次のコマンドを実行します。

[source,bash,role="execute"]
----
oc project app-management
----

### Adding Persistent Volume Claims
OpenShift に、外部の永続ストレージを表す `PersistentVolume` オブジェクトを作成し、それをコンテナーのファイルシステム内に *mounted* するように指示する方法は次のとおりです。

[source,bash,role="execute"]
----
oc set volume deploy/mapit --add --name=mapit-storage -t pvc --claim-mode=ReadWriteOnce --claim-size=1Gi --claim-name=mapit-storage --mount-path=/app-storage
----

出力は次のようになります。

----
deployment.apps/mapit volume updated
----

最初のステップで、*PersistentVolumeClaim* が作成されました。 このオブジェクトは、ユーザーから OpenShift への特定の容量を持つ、特定の種類のストレージの要求を表します。

次に、このストレージを参照するように `mapit` の「Deployment」を更新し、ポッド内の `/app-storage` ディレクトリで使用できるようにします。

新しい `Deployment` は次のように表示されます。

[source,bash,role="execute"]
----
oc get deploy mapit
----

出力には、「AGE」列を調べることで、新しいデプロイが作成されたことが示されます。

----
NAME    READY   UP-TO-DATE   AVAILABLE   AGE
mapit   1/1     1            1           14m
----

おそらく、コマンドをいつ実行したかによって、新しいポッドがまだ生成されていることがわかる場合とわからない場合があります。

[source,bash,role="execute"]
----
oc get pod
----

----
NAME             READY     STATUS              RESTARTS   AGE
mapit-3-ntd9w    1/1       Running             0          9m
mapit-4-d872b    0/1       ContainerCreating   0          5s
mapit-4-deploy   1/1       Running             0          10s
----

今すぐ `Deployment` を見てください:

[source,bash,role="execute"]
----
oc describe deploy mapit
----

新しいストレージに関する「Mounts」と「Volumes」の両方の詳細が表示されます。

----
...
    Mounts:
      /app-storage from mapit-storage (rw)
  Volumes:
   mapit-storage:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  mapit-storage
    ReadOnly:   false
...
----

しかし、カバーの下で何が起こっているのでしょうか?

### Storage Classes
OpenShift 4 が最初にインストールされたとき、AWS EBS の動的ストレージ プロバイダーが構成されました。 この `StorageClass` は次のように表示できます。

[source,bash,role="execute"]
----
oc get storageclass
----

And 次のようなものが表示されます。

----
NAME            PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
gp2 (default)   kubernetes.io/aws-ebs   Delete          WaitForFirstConsumer   true                   47m
gp2-csi         ebs.csi.aws.com         Delete          WaitForFirstConsumer   true                   47m
----

`StorageClass` を指定しないボリュームのリクエスト (`PersistentVolumeClaim`) が行われると、デフォルトが使用されます。 この場合、デフォルトは、要求されたサイズ (この例では 1Gi) の EBS GP2 ボリュームを作成する EBS プロビジョナーです。

[Note]
====
`gp2-csi` もあります。 これは、「Container Storage Interface」の略である https://github.com/container-storage-interface/spec[CSI Interface] を実装します。 この仕様により、ストレージ ベンダーはプラグインを一度開発すれば、さまざまなコンテナ オーケストレーション システムで動作させることができます。
====

### Persistent Volume (Claims)
前に実行したコマンドは「クレーム」を参照していました。 Kubernetes 環境のストレージは、ボリューム クレームとボリュームのシステムを使用します。 ユーザーが `PersistentVolumeClaim` を作成すると、Kubernetes は一致する `PersistentVolume` を見つけようとします。 ボリュームがまだ存在しない場合、要求を満たす動的プロビジョナーがあれば、 `PersistentVolume` が作成されます。

以下を実行します。

[source,bash,role="execute"]
----
oc get persistentvolume
----

次のようなものが表示されます。

----
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                          STORAGECLASS   REASON   AGE
pvc-4397c6be-9f53-490e-960d-c1b77de6000c   1Gi        RWO            Delete           Bound    app-management/mapit-storage   gp2                     12m
----
これは、以前の請求の結果として作成されたボリュームです。 ボリュームは、「app-management」プロジェクトに存在するクレームに *bound* されていることに注意してください。

次に、実行します。

[source,bash,role="execute"]
----
oc get persistentvolumeclaim -n app-management
----

次のようなものが表示されます。

----
NAME            STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
mapit-storage   Bound    pvc-4397c6be-9f53-490e-960d-c1b77de6000c   1Gi        RWO            gp2            14m
----

`pod` は作成されたストレージをマウントする必要があるため、ロールアウトが行われています。

[source,bash,role="execute"]
----
oc rollout status deployment mapit -n app-management
----

### Testing Persistent Storage

`oc` クライアントのリモートシェル機能を使用してポッドにログオンします。

[source,bash,role="execute"]
----
oc rsh $(oc get pods -l deployment=mapit -o name)
----

*コンテナーのシェル セッション* で、コンテナーの名前空間の観点からルート ディレクトリの内容を一覧表示します。

[source,bash,role="execute"]
----
ls -ahl /
----

そこに `/app-storage` というディレクトリが表示されます。

----
total 20K
drwxr-xr-x.   1 root  root         81 Apr 12 19:11 .
drwxr-xr-x.   1 root  root         81 Apr 12 19:11 ..
-rw-r--r--.   1 root  root        16K Dec 14  2016 anaconda-post.log
drwxrwsr-x.   3 root  1000570000 4.0K Apr 12 19:10 app-storage <1>
lrwxrwxrwx.   1 root  root          7 Dec 14  2016 bin -> usr/bin
drwxrwxrwx.   1 jboss root         45 Aug  4  2017 deployments
drwxr-xr-x.   5 root  root        360 Apr 12 19:11 dev
drwxr-xr-x.   1 root  root         93 Jan 18  2017 etc
drwxr-xr-x.   2 root  root          6 Nov  5  2016 home
lrwxrwxrwx.   1 root  root          7 Dec 14  2016 lib -> usr/lib
lrwxrwxrwx.   1 root  root          9 Dec 14  2016 lib64 -> usr/lib64
drwx------.   2 root  root          6 Dec 14  2016 lost+found
drwxr-xr-x.   2 root  root          6 Nov  5  2016 media
drwxr-xr-x.   2 root  root          6 Nov  5  2016 mnt
drwxr-xr-x.   1 root  root         19 Jan 18  2017 opt
dr-xr-xr-x. 183 root  root          0 Apr 12 19:11 proc
dr-xr-x---.   2 root  root        114 Dec 14  2016 root
drwxr-xr-x.   1 root  root         21 Apr 12 19:11 run
lrwxrwxrwx.   1 root  root          8 Dec 14  2016 sbin -> usr/sbin
drwxr-xr-x.   2 root  root          6 Nov  5  2016 srv
dr-xr-xr-x.  13 root  root          0 Apr 10 14:34 sys
drwxrwxrwt.   1 root  root         92 Apr 12 19:11 tmp
drwxr-xr-x.   1 root  root         69 Dec 16  2016 usr
drwxr-xr-x.   1 root  root         41 Dec 14  2016 var
----
**<1>** これは、コンテナ内の永続ストレージが表示される場所です

Amazon EBS ボリュームは、一度だけ読み書きできます。 つまり、これらはブロック ストレージであるため、一度に 1 つの EC2 インスタンスにのみアタッチできます。つまり、一度に 1 つのコンテナーのみが EBS ベースの `PersistentVolume` を使用できます。 つまり、読み書きは 1 回だけです。

リモート シェル セッション内で次を実行します。

[source,bash,role="execute"]
----
echo "Hello World from OpenShift" > /app-storage/hello.txt
exit
----

次に、ファイルが存在することを確認します。

[source,bash,role="execute"]
----
oc rsh $(oc get pods -l deployment=mapit -o name) cat /app-storage/hello.txt
----

ここで、永続ストレージが実際に機能することを確認するために、ポッドを削除します。

[source,bash,role="execute"]
----
oc delete pods -l deployment=mapit && oc rollout status deployment/mapit
----

`deployment` は、新しい `pod` を自動的にロールアウトします。

[source,bash,role="execute"]
----
oc get pods
----

新しいポッドの準備ができて実行中です。 実行されたので、ファイルを確認します。

[source,bash,role="execute"]
----
oc rsh $(oc get pods -l deployment=mapit -o name) cat /app-storage/hello.txt
----

それはまだそこにあります。 実際、新しいポッドは古いポッドと同じノードで実行されていない可能性もあります。つまり、内部では、Kubernetes と OpenShift が実際の外部ストレージを適切な場所に適切なタイミングで自動的に接続していることを意味します。

読み書き多用のストレージが必要な場合は、ファイルベースのストレージ ソリューションがそれを提供できます。 OpenShift Container Storage は、OpenShift 内で実行できるハイパーコンバージド ストレージ ソリューションであり、ローカルに接続されたストレージ デバイスをストレージ プールに変換し、そこからボリュームを作成することで、ファイル、ブロック、さらにはオブジェクト ストレージを提供します。