## MachineSets, Machines, and Nodes

Kubernetes の `Nodes` は、コンテナーがオーケストレーションされ、 `Pods` で実行される場所です。 OpenShift 4 は、 `Operators` の使用による自動化された操作に重点を置いているという点で、OpenShift 3 とは根本的に異なります。  `Nodes` に関しては、クラスター サイズの状態を維持することに重点を置いた一連の `Operator` とコントローラーがあります。これには、 `Nodes` の作成と破棄が含まれます。

### MachineSets and Machines
アプリケーション管理の演習で見たように、`ReplicaSet`/`ReplicationController` とそれが作成する `Pod` の間には基本的な基本的な関係があります。 同様に、MachineSet と Machine の間にも関係があります。

 `MachineSet` は、一連の `Machine` オブジェクトの望ましい状態を定義します。 IPI インストールを使用する場合、各 `Machine` の基礎となるインスタンスが実際に存在することを確認し、最後にすべての `Machine` が `Nodes` になるようにする `Operator` があります。

以下を実行します。

[source,bash,role="execute"]
----
oc get machineset -n openshift-machine-api
----

次のようなものが表示されます。

----
NAME                                    DESIRED   CURRENT   READY   AVAILABLE   AGE
cluster-6ljsd-9b8vz-worker-us-east-2a   1         1         1       1           167m
cluster-6ljsd-9b8vz-worker-us-east-2b   1         1         1       1           167m
cluster-6ljsd-9b8vz-worker-us-east-2c   0         0                             167m
----

OpenShift がインストールされると、インストーラーはクラウド プロバイダーに問い合わせて、利用可能な AZ について調べました (これは AWS 上にあるため)。 次に、最終的に各 AZ の `MachineSet` を作成し、必要な数の `Machine` に達するまで、これらのセットを順番にスケーリングしました。 デフォルトのインストールには 2 つのワーカーがあるため、最初の 2 つの AZ にはそれぞれ 1 つのワーカーが割り当てられます。 残りはゼロになりました。

[source,bash,role="execute"]
----
oc get machine -n openshift-machine-api
----

次のようなものが表示されます。

----
NAME                                         INSTANCE              STATE     TYPE         REGION      ZONE         AGE
cluster-f4a3-lpxbs-master-0                  i-04280885cafad3130   running   m4.xlarge    us-east-2   us-east-2a   47h
cluster-f4a3-lpxbs-master-1                  i-0def910edcae51d11   running   m4.xlarge    us-east-2   us-east-2b   47h
cluster-f4a3-lpxbs-master-2                  i-0beb5e40214d706fc   running   m4.xlarge    us-east-2   us-east-2c   47h
cluster-f4a3-lpxbs-worker-us-east-2a-b94pr   i-0a922c0fe765caa3c   running   m5.2xlarge   us-east-2   us-east-2a   47h
cluster-f4a3-lpxbs-worker-us-east-2b-m8gbx   i-0fb8d960b8a3a3343   running   m5.2xlarge   us-east-2   us-east-2b   47h
cluster-f4a3-lpxbs-worker-us-east-2c-5tmg7   i-0151c72cd85f85038   running   m5.2xlarge   us-east-2   us-east-2c   47h
----

各 `Machine` には、対応する `INSTANCE` があります。 これらの ID に見覚えはありますか? これらは AWS EC2 インスタンス ID です。 OpenShift マスターの `Machines` も表示されます。 それらはある程度ステートフルであり、それらの管理は異なるオペレーターによって、異なるプロセスを通じて処理されるため、 `MachineSet` の一部ではありません。

[Warning]
====
現在、マスターの `Machines` に対する保護はありません。 誤ってまたは意図的に削除しないでください。クラスターが破損する可能性があります。 修理可能ですが、楽しくありません。
====

最後に、次を実行します。

[source,bash,role="execute"]
----
oc get nodes
----

次のようなものが表示されます。

----
NAME                                         STATUS   ROLES    AGE     VERSION
ip-10-0-186-197.us-east-2.compute.internal   Ready    master   4h5m    v1.22.3+e790d7f
ip-10-0-190-214.us-east-2.compute.internal   Ready    master   4h6m    v1.22.3+e790d7f
ip-10-0-199-60.us-east-2.compute.internal    Ready    worker   3h53m   v1.22.3+e790d7f
ip-10-0-216-121.us-east-2.compute.internal   Ready    worker   3h53m   v1.22.3+e790d7f
ip-10-0-231-224.us-east-2.compute.internal   Ready    worker   3h53m   v1.22.3+e790d7f
ip-10-0-244-159.us-east-2.compute.internal   Ready    master   4h6m    v1.22.3+e790d7f
----

各 `Machine` は最終的に `Node` に対応します。 IPI では、マシン オペレーターが EC2 インスタンスを作成し、RHEL CoreOS オペレーティング システム内の Ignition がオペレーターから最初の指示を受け取るブートストラップ プロセスがあります。 これにより、EC2 インスタンスが OpenShift ノードとして構成され、クラスターに参加します。

`oc describe` とさまざまな `Machine` および `Node` オブジェクトをしばらく使用すると、どのオブジェクトがどのオブジェクトと関連しているかがわかります。

### Cluster Scaling
 `Operators` の魔法と、OpenShift が `Operators` を使用して `Machines` と `Nodes` を管理する方法により、OpenShift 4 でクラスターをスケーリングすることは非常に簡単です。

 `MachineSets` のリストをもう一度見てください。

[source,bash,role="execute"]
----
oc get machineset -n openshift-machine-api
----

そのリスト内で、 `oc scale` コマンドを使用して `MachineSet` オブジェクトの 1 つをスケーリングします。 走る：

[source,bash,role="execute"]
----
CLUSTERNAME=$(oc get  infrastructures.config.openshift.io cluster  -o jsonpath='{.status.infrastructureName}')
ZONENAME=$(oc get nodes -L topology.kubernetes.io/zone  --no-headers  | awk '{print $NF}' | tail -1)
oc scale machineset ${CLUSTERNAME}-worker-${ZONENAME} -n openshift-machine-api --replicas=2
----

スケーリングされた `MachineSet` は、ラボ ガイドに示されているものとは異なる可能性があることに注意してください。  `MachineSet` が正常にスケーリングされたというメモが表示されるはずです。 それでは、`Machines` のリストを見てください:

[source,bash,role="execute"]
----
oc get machines -n openshift-machine-api
----

おそらく、`Pending` の `STATE` を持つ 2 つの新しい `Machine` の新しいエントリが既にあるはずです。 しばらくすると、両方が対応する EC2 インスタンス ID を持ち、次のようになります。

----
cluster-f4a3-lpxbs-worker-us-east-2c-h7gdt   i-0b9208ec47f0e206b   running   m5.2xlarge     us-east-2   us-east-2c   47s
----

この時点で、バックグラウンドで、ブートストラップ プロセスが自動的に行われます。 数分後 (最大 5 分程度)、次の出力を確認します。

[source,bash,role="execute"]
----
oc get nodes
----

新鮮で幸せな新しいノードが表示されるはずです。 彼らは非常に若い年齢のものです：

----
ip-10-0-166-103.us-east-2.compute.internal   Ready    worker   1m   v1.16.2
----

[Note]
====
 `Machine` が準備され、 `Node` として追加されるまでに数分かかる場合があります。 必要に応じて、 `oc get nodes` に対して `watch` を実行することで、プロセスをたどることができます。
====

続行する前に、`MachineSet` を 2 つから 1 つにスケールダウンします。

[Warning]
====
${CLUSTER NAME} 変数と ${ZONE NAME} 変数を、数ステップ前にスケールアップしたときに設定したことを確認してください。
====

[source,bash,role="execute"]
----
oc scale machineset ${CLUSTERNAME}-worker-${ZONENAME} -n openshift-machine-api --replicas=1
----